### PR TITLE
Add Reason support

### PR DESCRIPTION
**Pull request by vladimyr**
Obtain OCaml version using `-vnum` flag.
Extend conditions to match projects using jbuild, esy, or merlin.

### CODE REVIEW

**Comment by hkmatsumoto** [comment]
Wonderful suggestion of `-vnum` I didn't know such an option existed! :tada:

Apart from that, I can't judge integrating OCaml and Reason support together is a good idea as I've never used Reason before.

**Comment by hkmatsumoto** [comment]
I've just tried Reason by reading its docs and I find the language transpiles to JavaScript without outputting OCaml files.
By this, I think making OCaml and Reason support into a single module isn't reasonable.

What do you say to send a separate PR containing Reason support?

**Comment by vladimyr** [comment]
> I've just tried Reason by reading its docs and I find the language transpiles to JavaScript without outputting OCaml files.

Not necessarily. Reason is OCaml's syntax extension (alternative frontend) and can be used in regular, compile to the native, workflow. The best example of such usage is https://github.com/Schniz/fnm or https://github.com/esy/esy They are both written using Reason syntax but compiled to native binaries.

There is no point in doing separate Reason PR because it is not a language with separate toolchain but alternative syntax that leverages existing OCaml's ecosystem.

**Comment by hkmatsumoto** [comment]
Just a question, Reason files are sometimes evaluated by OCaml's compiler?
If so, I'll embrace these changes as it looks nice to have OCaml version displayed in Reason projects.

By the way, please make sure to confirm the tests are passing locally since CI systems are not set up on this fork repository.

**Comment by vladimyr** [comment]
Yeah, Reason source files can be compiled using OCaml's compiler same way as standard `.ml` sources.

I tested this locally and the complete test suite passed.

**Comment by hkmatsumoto** [comment]
LGTM, thanks for the changes :tada:

**Pull request merged**
